<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\Criteria;

/**
 * BookedslotproRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookedslotproRepository extends EntityRepository {

	function findByStandAndCalendar($idStand, $idCalendar) {
		$repository = $this->getEntityManager()->getRepository('ApiBundle:Stand');
		$Stand = $repository->find($idStand);
		$repository = $this->getEntityManager()->getRepository('ApiBundle:Calendar');
		$Calendar = $repository->find($idCalendar);
		$repository = $this->getEntityManager()->getRepository('ApiBundle:Bookedslot');
		$criteria = new Criteria();
		$criteria->where($criteria->expr()->eq('idstand', $Stand));
		$criteria->andWhere($criteria->expr()->lte('fromtime', $Calendar->getStartDate()));
		$criteria->andWhere($criteria->expr()->gte('totime', $Calendar->getEndDate()));
		$Bookedslot = $repository->matching($criteria)->first();
		return [
			$Stand, 
			$Calendar, 
			$Bookedslot
		];
	}
}
